### ISSUE TITLE
Unable to load on plain 1.21

### ISSUE THREAD

**Issue by RedxAx** [toxicity188/ModelAnimator#1]
Log:
```
[08:29:51] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.method_34538(class_757.java:537) [client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	... 13 more
Caused by: net.irisshaders.iris.helpers.FakeChainedJsonException: Invalid shaders/core/rendertype_entity_translucent.json: 
	at net.minecraft.class_2973.handler$cbc000$iris$changeShaderParseException(class_2973.java:516) ~[client-intermediary.jar:?]
	at net.minecraft.class_2973.method_12856(class_2973.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:498) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	... 13 more
Caused by: net.irisshaders.iris.gl.shader.ShaderCompileException: rendertype_entity_translucent.vsh: rendertype_entity_translucent.vsh: 0(110) : error C1102: incompatible type for parameter #1 ("pos.21")
0(110) : error C7623: implicit narrowing of type from "vec3" to "int"
0(110) : error C1104: too many parameters in function call
0(209) : error C1102: incompatible type for parameter #1 ("pos.21")
0(209) : error C7623: implicit narrowing of type from "vec3" to "int"
0(209) : error C1104: too many parameters in function call

	at net.minecraft.class_281.handler$ccm000$iris$causeException(class_281.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_34416(class_281.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:210) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:498) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	... 13 more
	```

**Comment by toxicity188** [comment]
Not happened in 1.21.1 sodium/iris; skipped.

**Comment by RedxAx** [comment]
I faced the same thing on 1.21.1 Sodium & Iris 
[latest.log](https://github.com/user-attachments/files/17796438/latest.log)

**Comment by RedxAx** [comment]
> I faced the same thing on 1.21.1 Sodium & Iris [latest.log](https://github.com/user-attachments/files/17796438/latest.log)

@toxicity188

**Comment by toxicity188** [comment]
I checked 1.0 jar is different to master src :(
Download 1.1

**Comment by RedxAx** [comment]
> I checked 1.0 jar is different to master src :( Download 1.1

Yup! Works now, thank you <3
Do you plan on supporting shaders in the future (Iris Shaders)?
That would be so cool, Magic Gesture did it by the way
